export const GAME_PLAYER_CHANGE_TYPE = Symbol('GAME_PLAYER_CHANGE_TYPE')
export const GAME_PLAYER_CHANGE_COLOR = Symbol('GAME_PLAYER_CHANGE_COLOR')
export const GAME_PLAYER_SELECTED = Symbol('GAME_PLAYER_SELECTED')
export const GAME_STARTED = Symbol('GAME_STARTED')
